version: "3.9"
services:
  testsite:
    container_name: nginx #jekyll
    image: nginx:nix #jekyll-site:latest #rails-app:latest
#    environment:
#    command: ["jekyll", "serve", "--watch"]
#    volumes:
#      - ./test_site:/test_site
    restart: always
    networks:
      - site_network
    ports:
#      - "4000:4000"
      - "8000:81"
networks:
  site_network:
